CC=pgcc
RM=rm -f
#CXXFLAGS=-Wall -Wconversion -g
CXXFLAGS=-Wall -Wconversion -O3
LDFLAGS=-g
LDLIBS=-lfftw3 -lfftw3f -lm -lrt

DESTS=experiment generate_graphs kaiserbessel
SRCS:=$(filter-out $(DESTS:%=%.cc), $(wildcard *.cc))
OBJS:=$(subst .cc,.o,$(SRCS))

all: $(DESTS)

$(DESTS): $(OBJS)

clean:
	$(RM) *.o $(DESTS)
